version: '2'
services:
    sonar:
        extends:
            file: services/sonar.yml
            service: sonar
    mariadb:
        extends:
            file: services/mariadb.yml
            service: mariadb
    kafka:
        image: spotify/kafka
        ports:
            - 9092:9092
            - 2181:2181
        environment:
            - ADVERTISED_HOST=localhost
            - ADVERTISED_PORT=9092
    jhipster-registry:
        extends:
            file: services/jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
